# Publishes a clean export of this repository to GitHub (3esign/beops) as open source.
# Internal working documents (research/06-paper, research/_trail, research/01-programme) stay local: the
# public repository carries the registry, the provenance index, the corrections, the collectors, the organs,
# the tools and the site - the observatory, not its drafts.
# Why an export and not `git push`: the local history carries a 141 MB evidence blob that GitHub
# refuses (>100 MB), and research/evidence/ (585 MB of captured third-party pages) stays local by
# rule - it is proof, not publication. The public repository therefore receives the current tree
# minus evidence, scratch, archives, runtime and live data, as ONE commit per publish, with the
# local commit hash in the message. Local history is never rewritten.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\publish_github.ps1            # publish
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\publish_github.ps1 -DryRun    # show what would go
param([switch]$DryRun)
$ErrorActionPreference = 'Stop'
function Resolve-BeopsPython {
  if ($env:BEOPS_PYTHON -and (Test-Path $env:BEOPS_PYTHON)) { return $env:BEOPS_PYTHON }
  $svemirPython = 'C:\Svemir\python.cmd'
  if (Test-Path $svemirPython) { return $svemirPython }
  $bundled = Join-Path $env:USERPROFILE '.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe'
  if (Test-Path $bundled) { return $bundled }
  return 'python'
}
function Resolve-BeopsTestPython {
  if ($env:BEOPS_TEST_PYTHON -and (Test-Path $env:BEOPS_TEST_PYTHON)) { return $env:BEOPS_TEST_PYTHON }
  return (Resolve-BeopsPython)
}
$src = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$projectParent = Split-Path $src -Parent
$pub = if ($env:BEOPS_PUBLIC_ROOT) { $env:BEOPS_PUBLIC_ROOT } else { Join-Path $projectParent 'Beops-public' }
$py = Resolve-BeopsPython
$remote = 'https://github.com/3esign/beops.git'
$exclude = @('research/evidence','research/_scratch','research/06-paper','research/_trail','research/01-programme','archive','runtime','data/live','node_modules',
             'research/06-paper/conference/Prvi-poziv-2026.pdf','research/06-paper/conference/Uputstvo-za-autore3.pdf',
             'research/06-paper/conference/call-1.png','research/06-paper/conference/call-2.png','research/06-paper/conference/call-3.png',
             'research/evidence/S158')
Set-Location $src
$null = New-Item -ItemType Directory -Path (Join-Path $src 'runtime') -Force
$head = (git rev-parse --short HEAD).Trim()
$files = (git ls-files) -split "`n" | Where-Object { $_ -ne '' }
$keep = $files | Where-Object { $f = $_; -not ($exclude | Where-Object { $f -eq $_ -or $f.StartsWith($_ + '/') }) }
# C-020, second occurrence. The folder list above excludes research/06-paper, so pre-papers and
# working documents never reach the export - but research/07-legal is exported whole, and the letters
# live there. The site build calls letters internal by name (NOT_PUBLIC in tools/build_site.py) while
# this export published them, which is the same policy answering two different ways depending on which
# door a document walks through. The categories are named here too, by FILENAME, so a new document of
# an internal kind is excluded by being that kind rather than by someone remembering to list it.
$notPublic = @('PISMA','LETTER','WORKING_DOCUMENT','INTERNAL','DRAFT','PRESEK','PRE_PAPER','PREPAPER','PRED_RAD')
$keep = $keep | Where-Object { $n = (Split-Path $_ -Leaf).ToUpper(); -not ($notPublic | Where-Object { $n.Contains($_) }) }
Write-Output ("source commit {0}: {1} tracked files, {2} exported" -f $head, $files.Count, $keep.Count)
if ($DryRun) { $keep | Select-Object -First 40; exit 0 }
# C-045 left this open: two publish paths - the scheduled tick and any ship batch - run against one
# export repository with no coordination, and the loser of a race for git's index.lock read exactly
# like a clean tree. The race is now refused rather than lost silently. A lock older than fifteen
# minutes is treated as abandoned, because a publish that takes that long has died.
$lockFile = Join-Path $src 'runtime\publish.lock'
if (Test-Path $lockFile) {
  $age = (Get-Date) - (Get-Item $lockFile).LastWriteTime
  if ($age.TotalMinutes -lt 15) {
    Write-Output ("STOP: another publish holds the lock (taken {0:N1} min ago). NOTHING WAS PUBLISHED." -f $age.TotalMinutes)
    exit 4
  }
  Write-Output ("note: a publish lock {0:N1} min old was abandoned and is being taken over." -f $age.TotalMinutes)
}
Set-Content -Path $lockFile -Value ("pid $PID at " + (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')) -Encoding UTF8
try {

# the site: docs/ is what GitHub Pages serves (main branch, /docs). It is GENERATED by
# tools/build_site.py from the registry, the provenance index, the corrections and the last export,
# so the public page cannot state a number the files do not support.
& $py -X utf8 -B tools\build_site.py
# the three maps of the document, regenerated from the snapshot the site is about to serve
& $py -X utf8 -B tools\make_maps.py --out docs | Out-Null

# ---------------------------------------------------------------- PUBLISH GATE
# Every ship batch ran the full suite and refused to commit when it failed. The scheduled publish
# fired every ten minutes, rebuilt the site and pushed it without running a single test - so the gate
# protected the rare path and not the common one, and the common one is how the public site actually
# updates. The gate lives here, after the site is built and before anything is copied, committed or
# pushed, so that THE THING THAT PUBLISHES IS THE THING THAT CHECKS and no future caller can publish
# by forgetting.
#
# On failure nothing is copied into the export, nothing is committed and nothing is pushed: the
# published site stays exactly as it was. The export working tree may be left half-rebuilt, which is
# harmless because every publish clears and rebuilds it from scratch - but the LAST PUBLISHED COMMIT
# is untouched, which is the part that matters.
#
# A frozen site must not be a quiet site. Every run writes data/live/publish-receipt.json and
# tools/guard.py reads it, so a suite that has been failing for half an hour becomes a STOP rather
# than a silence - the lesson C-036 bought for the organs, applied to the publisher.
$testsOut = Join-Path $src 'runtime\publish-tests.txt'
$gatePy = Resolve-BeopsTestPython
$prevEAP = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
& $gatePy -X utf8 -B -m unittest discover -s research -p "test_*.py" *> $testsOut
$testsRc = $LASTEXITCODE
$ErrorActionPreference = $prevEAP
$summary = ''
if (Test-Path $testsOut) {
  $summary = ((Get-Content $testsOut | Select-String -Pattern '^Ran |^OK$|^FAILED') -join ' ').Trim()
}
$receipt = [ordered]@{
  schema      = 'beops-publish-receipt/v1'
  at          = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
  source_head = $head
  tests_ok    = ($testsRc -eq 0)
  tests       = $summary
  published   = $false
  why         = ''
}
if ($testsRc -ne 0) {
  $first = ''
  if (Test-Path $testsOut) {
    $raw = Get-Content $testsOut -Raw
    $i = $raw.IndexOf('FAIL:'); if ($i -lt 0) { $i = $raw.IndexOf('ERROR:') }
    if ($i -ge 0) { $first = $raw.Substring($i, [Math]::Min(400, $raw.Length - $i)) }
  }
  $receipt.why = "the suite did not pass, so nothing was published. $first"
  $receipt | ConvertTo-Json -Depth 4 | Set-Content -Path (Join-Path $src 'data\live\publish-receipt.json') -Encoding UTF8
  Write-Output "STOP: the suite did not pass ($summary). NOTHING WAS PUBLISHED and the site stays as it was."
  Write-Output $first
  # PowerShell does not run a finally block on `exit`, and a lock left behind by a failing gate would
  # block every publish for the next fifteen minutes - a second outage caused by the first.
  Remove-Item $lockFile -Force -ErrorAction SilentlyContinue
  exit 3
}
Write-Output "gate: $summary"
# ------------------------------------------------------------ END PUBLISH GATE

if (-not (Test-Path $pub)) { New-Item -ItemType Directory -Path $pub | Out-Null; git -C $pub init -q -b main }
# clear the export tree (never the .git of the export repo), after the gate has passed
Get-ChildItem -Path $pub -Force | Where-Object { $_.Name -ne '.git' } | Remove-Item -Recurse -Force
foreach ($f in $keep) {
  $d = Split-Path (Join-Path $pub $f)
  if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null }
  Copy-Item -LiteralPath (Join-Path $src $f) -Destination (Join-Path $pub $f) -Force
}
if (Test-Path (Join-Path $src 'docs')) { Copy-Item -LiteralPath (Join-Path $src 'docs') -Destination $pub -Recurse -Force }
# evidence placeholder so links in the index explain themselves
$note = @'
# research/evidence

The captured pages, headers, robots.txt files and hashes (585 MB) that prove each permission live on the authors' own machine and are not republished: they are third-party content kept as evidence, not as publication. Every capture is listed with its SHA-256 in `research/08-provenance/INDEX.md` and `LEDGER.jsonl`; a reviewer may request any capture by id.
'@
New-Item -ItemType Directory -Path (Join-Path $pub 'research/evidence') -Force | Out-Null
Set-Content -Path (Join-Path $pub 'research/evidence/README.md') -Value $note -Encoding UTF8
$note2 = @'
# research/06-paper, research/_trail, research/01-programme

The working documents, pre-papers, research trails and programme notes are internal and stay on the authors' own machine. The public repository carries the observatory itself: the source registry, the provenance index and ledger, the corrections, the collectors, the organ register, the tools, the tests and the generated site. Links into these folders from the research index are therefore not resolvable here.
'@
foreach ($d in @('research/06-paper','research/_trail','research/01-programme')) { New-Item -ItemType Directory -Path (Join-Path $pub $d) -Force | Out-Null; Set-Content -Path (Join-Path $pub "$d/README.md") -Value $note2 -Encoding UTF8 }
git -C $pub add -A
# The source .gitignore travels with the export and lists docs/ (generated locally, never committed
# in the source repo). In the EXPORT repo docs/ is the published site, so it must be forced in.
# Without -f, only the files added before that ignore rule existed stayed tracked, and every page
# added later - monolog.html, basemap-belgrade.json - was silently dropped and served as 404.
git -C $pub add -A -f docs
# One commit per publish: the public history becomes a free archive of what the observatory held at
# each moment - the "git scraping" pattern - and a second, independent record against our own receipts.
$snap = Join-Path $src 'public\live-snapshot.json'
$asof = if (Test-Path $snap) { try { (Get-Content $snap -Raw | ConvertFrom-Json).as_of } catch { '' } } else { '' }
$msg = if ($asof) { "Live snapshot $asof (export of $head)" } else { "Publish export of local commit $head ($(Get-Date -Format 'yyyy-MM-dd HH:mm') local)" }
# On 2026-09-10 this said "nothing changed since the last publish" and exited 0 while seventeen
# files sat staged in the export, so the site stayed a commit behind until somebody ran it by hand.
# The check could not tell an EMPTY status from an UNREADABLE one - git returning nothing because
# there is nothing to say, and git returning nothing because it failed (an index.lock held by the
# scheduled publish running at the same moment reads exactly like a clean tree). That is the
# watchman's second lie - calling blindness success - committed by the publish path.
# So the exit code is consulted, and a status that could not be read is never reported as clean.
$status = git -C $pub status --porcelain 2>&1
$rc = $LASTEXITCODE
if ($rc -ne 0) {
  Write-Output "STOP: could not read the export status (git exit $rc). Nothing was published, and this is NOT 'nothing changed'."
  exit 2
}
$changed = @($status | Where-Object { $_ -ne $null -and "$_".Trim() -ne '' }).Count -gt 0
if (-not $changed) {
  $receipt.published = $false
  $receipt.why = 'nothing changed since the last publish'
  $receipt | ConvertTo-Json -Depth 4 | Set-Content -Path (Join-Path $src 'data\live\publish-receipt.json') -Encoding UTF8
  Write-Output 'nothing changed since the last publish'
  Remove-Item $lockFile -Force -ErrorAction SilentlyContinue
  exit 0
}
git -C $pub -c user.name='Semir Poturak' -c user.email='scumutator@gmail.com' commit -q -m $msg
if (-not (git -C $pub remote | Select-String -SimpleMatch 'origin')) { git -C $pub remote add origin $remote }
git -C $pub push -u origin main
$receipt.published = $true
$receipt.why = $msg
$receipt | ConvertTo-Json -Depth 4 | Set-Content -Path (Join-Path $src 'data\live\publish-receipt.json') -Encoding UTF8
Write-Output "published: $msg"

} finally { Remove-Item $lockFile -Force -ErrorAction SilentlyContinue }
